# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

arr1 = np.array([1, 2, 3])
# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3], [4,5,6]],[[7, 8, 9], [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr2.shape, arr2.ndim, arr1.dtype, arr1.size, type(arr1)

((2, 3), 2, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr_frame = pd.DataFrame(arr2)
arr_frame

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
ran_arr = np.arange(0, 100, 3)
ran_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0, 10, size = (7,2))
rand_arr

array([[4, 7],
       [1, 6],
       [4, 9],
       [6, 5],
       [5, 8],
       [4, 3],
       [1, 5]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr2 = np.random.random((3,5))
rand_arr2

array([[0.10634384, 0.00689299, 0.70525961, 0.68751806, 0.05531994],
       [0.76628223, 0.38385466, 0.22204237, 0.91855619, 0.07562672],
       [0.68069195, 0.71223254, 0.6082453 , 0.54016071, 0.41872012]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr3 = np.random.randint(0, 10, size = (4,6))
rand_arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr4 = np.random.randint(1, 10, size=(3,7))
# Find the unique numbers in the array you just created
np.unique(rand_arr4)

array([1, 2, 3, 4, 5, 7, 9])

In [15]:
# Find the 0'th index of the latest array you created
rand_arr4[0][0]

9

In [16]:
# Get the first 2 rows of latest array you created
rand_arr4[:2][:]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr4[:2,0:2]

array([[9, 1],
       [5, 3]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr5 = np.random.randint(0, 10, size = (3,5))
ones = np.ones((3,5))
rand_arr5

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [19]:
# Add the two arrays together
rand_arr5 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [21]:
# Try add the array of ones and the other most recent array together
rand_arr5 + ones.T

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
rand_arr6 = np.random.random((3,5))

In [23]:
# Subtract the new array of ones from the other most recent array
ones.T - rand_arr6

array([[0.22486718, 0.06050106, 0.10517265, 0.40210002, 0.07812576],
       [0.9115075 , 0.80401714, 0.95477271, 0.67466967, 0.61132271],
       [0.72865097, 0.17126249, 0.64324667, 0.71906549, 0.45730392]])

In [24]:
# Multiply the ones array with the latest array
ones.T * rand_arr6

array([[0.77513282, 0.93949894, 0.89482735, 0.59789998, 0.92187424],
       [0.0884925 , 0.19598286, 0.04522729, 0.32533033, 0.38867729],
       [0.27134903, 0.82873751, 0.35675333, 0.28093451, 0.54269608]])

In [25]:
# Take the latest array to the power of 2 using '**'
rand_arr6 **2

array([[0.60083089, 0.88265826, 0.80071599, 0.35748438, 0.84985211],
       [0.00783092, 0.03840928, 0.00204551, 0.10583982, 0.15107004],
       [0.0736303 , 0.68680586, 0.12727294, 0.0789242 , 0.29451904]])

In [26]:
# Do the same thing with np.square()
np.square(rand_arr6)

array([[0.60083089, 0.88265826, 0.80071599, 0.35748438, 0.84985211],
       [0.00783092, 0.03840928, 0.00204551, 0.10583982, 0.15107004],
       [0.0736303 , 0.68680586, 0.12727294, 0.0789242 , 0.29451904]])

In [27]:
# Find the mean of the latest array using np.mean()
np.mean(rand_arr6)

0.49689427089910315

In [28]:
# Find the maximum of the latest array using np.max()
np.max(rand_arr6)

0.9394989415641891

In [29]:
# Find the minimum of the latest array using np.min()
np.min(rand_arr6)

0.045227288910538066

In [30]:
# Find the standard deviation of the latest array
np.std(rand_arr6)

0.30048081329938187

In [31]:
# Find the variance of the latest array
np.var(rand_arr6)

0.09028871916105798

In [32]:
# Reshape the latest array to (3, 5, 1)
wellp = rand_arr6.reshape(3,5,1)
wellp

array([[[0.77513282],
        [0.93949894],
        [0.89482735],
        [0.59789998],
        [0.92187424]],

       [[0.0884925 ],
        [0.19598286],
        [0.04522729],
        [0.32533033],
        [0.38867729]],

       [[0.27134903],
        [0.82873751],
        [0.35675333],
        [0.28093451],
        [0.54269608]]])

In [33]:
# Transpose the latest array
wellp.T

array([[[0.77513282, 0.0884925 , 0.27134903],
        [0.93949894, 0.19598286, 0.82873751],
        [0.89482735, 0.04522729, 0.35675333],
        [0.59789998, 0.32533033, 0.28093451],
        [0.92187424, 0.38867729, 0.54269608]]])

What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(42)
mat1 = np.random.randint(0, 10, size = (3,3))
mat2 = np.random.randint(0, 10, size = (3,2))
mat2

array([[4, 3],
       [7, 7],
       [2, 5]])

In [35]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1, mat2)

array([[59, 74],
       [76, 99],
       [64, 83]])

In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(42)
mat3 = np.random.randint(0, 10, size = (4,3))
mat4 = np.random.randint(0, 10, size = (4,3))
mat4

array([[7, 2, 5],
       [4, 1, 7],
       [5, 1, 4],
       [0, 9, 5]])

In [37]:
# Perform a dot product on the two newest arrays you created
#np.dot(mat3, mat4)

It doesn't work. How would you fix it?

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat3, mat4.T)

array([[83, 76, 61, 62],
       [85, 85, 62, 99],
       [61, 63, 44, 89],
       [69, 68, 51, 62]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [40]:
# Compare the two arrays with '>'
mat3 > mat4

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [41]:
# Compare the two arrays with '>='
mat3 >= mat4

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [42]:
# Find which elements of the first array are greater than 7
mat3

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [43]:
# Which parts of each array are equal? (try using '==')
mat3 == mat4

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
# Sort one of the arrays you just created in ascending order
np.sort(mat3)

array([[3, 6, 7],
       [4, 6, 9],
       [2, 6, 7],
       [3, 4, 7]])

In [45]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat3)

array([[1, 0, 2],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [46]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat3)

5

In [47]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat3)

6

In [48]:
mat3

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [49]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat3, axis = 1)

array([2, 2, 2, 2], dtype=int64)

In [50]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(mat3, axis = 0)

array([2, 0, 0], dtype=int64)

In [53]:
# Create an array of normally distributed random numbers
n = np.random.randn(3,3)
n

array([[ 0.60344123, -0.25104397, -0.16386712],
       [-1.47632969,  1.48698096, -0.02445518],
       [ 0.35555132,  0.41701111,  0.83246186]])

In [52]:
# Create an array with 10 evenly spaced numbers between 1 and 100
space = np.arange(1, 100, 10)
space

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.